version: "3.9"
# サービスとは、全体を構成する一つ一つのコンテナのこと
services:
  app:
    # 使うイメージを指定
    image: gotodo
    # イメージのビルドに関する設定を書く
    build:
      args:
        - target=dev
    # Composeファイルのenvironment属性を使って、サービスのコンテナに環境変数を設定できます。
    # docker run -e VARIABLE=VALUE ... と同じように動作します。
    environment:
      TODO_ENV: dev
      APP_PORT: 8080
    volumes:
      - .:/app
    ports:
      # ホスト側の18000がコンテナの8080に対応している
      - "18000:8080"
